mixed-port: 7890
allow-lan: true
mode: rule
log-level: info

# ---------- PROVIDERS ----------
proxy-providers:
  black:
    type: http
    url: https://raw.githubusercontent.com/vfc11lork/home/main/BLACK_VLESS_RUS.txt
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

# ---------- GROUPS ----------
proxy-groups:
  - name: ğŸŒ EU-FAST
    type: url-test
    use:
      - black
    filter: "(Finland|Germany|Netherlands|Poland|Estonia)"
    url: http://www.gstatic.com/generate_204
    interval: 300

  - name: ğŸ® GAME
    type: select
    proxies:
      - ğŸŒ EU-FAST

  - name: ğŸ¤– CHATGPT
    type: select
    proxies:
      - ğŸŒ EU-FAST

  - name: ğŸ§­ DEFAULT
    type: select
    proxies:
      - ğŸŒ EU-FAST

# ---------- RULES ----------
rules:
  - DOMAIN-SUFFIX,roblox.com,ğŸ® GAME
  - DOMAIN-SUFFIX,rbxcdn.com,ğŸ® GAME

  - DOMAIN-SUFFIX,openai.com,ğŸ¤– CHATGPT
  - DOMAIN-SUFFIX,chatgpt.com,ğŸ¤– CHATGPT
  - DOMAIN-SUFFIX,oaistatic.com,ğŸ¤– CHATGPT
  - DOMAIN-SUFFIX,oaiusercontent.com,ğŸ¤– CHATGPT

  - GEOIP,RU,DIRECT
  - MATCH,ğŸ§­ DEFAULT
